name: matter-pi-gpio-commander
version: "1.1.0"
summary: Raspberry Pi GPIO as a Matter lighting app
description: Refer to https://snapcraft.io/matter-pi-gpio-commander

# Apart from WiringPi (LGPL-3.0-only), everything else has Apache-2.0 license
license: Apache-2.0 AND LGPL-3.0-only

grade: stable
confinement: strict

base: core22
architectures:
  - build-on: arm64

plugs:
  # This is to communicate with the OpenThread Border Router snap (https://snapcraft.io/openthread-border-router)
  # when enabling Thread on this application.
  otbr-dbus-wpan0:
    interface: dbus
    bus: system
    name: io.openthread.BorderRouter.wpan0

layout:
  /mnt:
    bind: $SNAP_COMMON/mnt

parts:
  wiring-pi:
    plugin: nil
    source: https://github.com/WiringPi/WiringPi.git
    source-depth: 1
    source-tag: 2.61-1
    override-build: |
      WIRINGPI_SUDO="" ./build

      mkdir -p $CRAFT_PART_INSTALL/lib
      cp -v /usr/local/lib/libwiringPi.so* $CRAFT_PART_INSTALL/lib/

      mkdir -p $CRAFT_PART_INSTALL/usr/share/doc/libwiringPi
      cp COPYING.LESSER $CRAFT_PART_INSTALL/usr/share/doc/libwiringPi/
    build-packages: [git, gcc, g++]

  test-blink:
    after: [wiring-pi]
    plugin: nil
    source: .
    override-build: |
      g++ -Wall test-blink.cpp -lwiringPi -o test-blink
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp test-blink $CRAFT_PART_INSTALL/bin/
  
  matter-sdk:
    plugin: matter-sdk
    matter-sdk-version: "1536ca20c5917578ca40ce509400e97b52751788" # use this commit with ptpython version fix; needs to be updated once matter sdk have a stable release
    matter-sdk-zap-version: "v2023.11.13"
  
  lighting:
    plugin: nil
    after: [wiring-pi, matter-sdk]
    source: app
    override-build: |
      cd ../../matter-sdk/build/matter-sdk
      source matter_sdk_env
      
      # Copy and replace the application files
      cp -vr $CRAFT_PART_BUILD/lighting-common/* examples/lighting-app/lighting-common/
      cp -vr $CRAFT_PART_BUILD/linux/* examples/lighting-app/linux

      cd examples/lighting-app/linux
      gn gen out/build
      ninja -C out/build

      ldd out/build/chip-lighting-app
      
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp out/build/chip-lighting-app $CRAFT_PART_INSTALL/bin/lighting-app        

  local-bin:
    plugin: nil
    source: snap/local/bin/
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -v run.sh $CRAFT_PART_INSTALL/bin/
      cp -v load-snap-options.sh $CRAFT_PART_INSTALL/bin/

apps:
  lighting:
    daemon: simple
    command-chain:
      - bin/load-snap-options.sh
    command: bin/run.sh
    install-mode: disable
    plugs:
      - network
      - network-bind
      - bluez
      - avahi-control
      - gpio-memory-control
      - otbr-dbus-wpan0

  help:
    command: bin/lighting-app -h

  # This app is to test the GPIO control without using a Matter controller
  test-blink:
    command-chain:
      - bin/load-snap-options.sh
    command: bin/test-blink
    plugs:
      - gpio-memory-control
